In [10]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

To install a Python library in Colab, you can use the `pip install` command within a code cell. For example, to install a library called `some_library`, you would run:

In [11]:
import numpy as np
import pandas as pd

In [12]:
# creating and loading data
a=[1,2,3,4,6,8,6]

In [13]:
s= pd.Series(a)

In [14]:
s

0    1
1    2
2    3
3    4
4    6
5    8
6    6
dtype: int64

In [15]:
d={"mahek":90,"rinkal":34,"krisha":46,"rashi":79}
s=pd.Series(d)
s

mahek     90
rinkal    34
krisha    46
rashi     79
dtype: int64

In [16]:
#  Make the Data frame
df=pd.DataFrame([d])
df

   mahek  rinkal  krisha  rashi
0     90      34      46     79

In [17]:
pd.DataFrame({
    "name":["aman","riya"],   # colum-1
    "salary":[40000,50000]    # colum-2
})

   name  salary
0  aman   40000
1  riya   50000

In [18]:
df = pd.read_csv("employees_100.csv")  # make the data frame
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [19]:
#inspecting before analyzing
# never start analyzing right after loading .read the data first .

# .head() - what does my datest look like?
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [20]:
# .tail() - what do the last rows look like?
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [21]:
# .sample() - what does a random slice look like?
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
46,182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28

In [22]:
# .shape - how many rows and colums do i have?
df.shape

(100, 10)

In [23]:
# .dtypes - what kind of data is stored in each column?
df.dtypes

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [24]:
# .info() - what is the overall structure and where are values missing?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [25]:
# .describe() - what do the basic statistics look like?
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [26]:
# how many null value we have?
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [27]:
#selcting and filtering data
# accessing single column
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: object

In [28]:
# accessing multiple column
df[["name","salary"]].head() # and u can also work in that

             name salary
0    Swati Kapoor  70719
1  Kavya Malhotra  77058
2    Manish Desai  69911
3        Neha Das  69993
4       Isha Nair  88216

In [29]:
# to make anyhting index
df = df.set_index("employee_id")   # make index them whoes value different for all

In [30]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [31]:
# to find any index details by their indexing(it can be anything like here employee_id)
df.loc[184]

name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 184, dtype: object

In [32]:
# multiple person details
df.loc[[184,171]]   # remember double [[]]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24

In [33]:
# to slice out some index
df.loc[184:171]  # dont need [[]]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24

In [34]:
# iloc only work on actual no index like 0123..
df.iloc[0:10]  # slicing

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [35]:
df.loc[154:145][["name","city","salary"]] # remeber[[]] in 2nd time

                       name       city salary
employee_id
154          Kavya Malhotra     Mumbai  77058
171            Manish Desai  Hyderabad  69911
146                Neha Das       Pune  69993
145               Isha Nair        NaN  88216

In [36]:
# you can use condition op in this and got ans in bollean
# you can use this for sceprate some dataes
df["age"]>40

employee_id
184    False
154    False
171    False
146    False
145    False
       ...
161    False
172    False
115     True
193    False
152     True
Name: age, Length: 100, dtype: bool

In [37]:
# to get ans in data not in boolean
# now you can seprate some data by condition
df[df["age"]>40]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [38]:
# give me people who working in finance and there age is grater than 40
df[((df["department"]=="Finance") | (df["department"]=="data science")) & (df["age"]>30) & (df["experience"]>3)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18

In [39]:
# Cleaning data
df.isnull() # it only give true and false of null value

df.isnull().sum() # you get some of this where true =1 and false=0

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [40]:
# fill the data
df2 = df.dropna()   # all the rows drop here who has null value
df2

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...
183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [41]:
df2.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [42]:
# to drop some specific column null value
df.dropna(subset=['city','age'])

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [43]:
 # just fill any specific colunm null value by there mean
df['age'].fillna(df["age"].mean)

employee_id
184                                                 38.0
154    <bound method Series.mean of employee_id\n184 ...
171                                                 23.0
146                                                 28.0
145                                                 32.0
                             ...
161                                                 22.0
172                                                 22.0
115                                                 43.0
193                                                 23.0
152                                                 44.0
Name: age, Length: 100, dtype: object

In [44]:
 # if you want to fill them in your real data
 # When your data doesn't vary much use "mean"
df["age"].fillna(df["age"].mean(),inplace = True)

In [45]:
# here all age null value is filled so when you write isnull() you age 0
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [46]:
# to change data type of salary for median
# here salary data type is objrct
# so we have to convert it data type in float for fill other data type
df['salary']= df['salary'].str.replace(",","", regex=False)

# here all the value we got error that save here and program will continue
# bad value become NaN,not a crash
df['salary']= pd.to_numeric(df['salary'],errors = 'coerce')

# here salary null values are filled
df['salary']=df['salary'].fillna(df['salary'].median())

In [47]:
df['salary'].dtype

dtype('float64')

In [48]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [49]:
# here we are going to fill the null values of department
df["department"].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [50]:
# .mode() → finds the most frequently occurring value
df["department"] = df['department'].fillna(df["department"].mode()[0])

In [51]:
df["city"] = df['city'].fillna(df["city"].mode()[0])

In [52]:
# Now all the data are fill up
df.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [53]:
# duplicate values
df.duplicated().sum()  # exact full-row duplicate

np.int64(0)

In [54]:
# to convrt it again into index from the employee_id indexing
df = df.reset_index()

In [55]:
# now we have 4 duplicate value
# because employee id should be change of every one
# but now employee id is not index so now can get there are duplicate
df.duplicated(subset=["employee_id"]).sum()  # duplicate by ID only

np.int64(4)

In [56]:
# to remove duplicates and see table without duplicate
df.drop_duplicates(subset=["employee_id"],keep = "first", inplace = True)  # now wew have 96 rows × 10 columns

In [57]:
# text --->real dates
df["joining_date"]=pd.to_datetime(df["joining_date"])

In [58]:
# rename any column/ row index name
#df.rename(columns={"OLD COLUMN": "NEW COLUMN"}, inplace=True)
df.rename(columns={"emp_name":"employee_name"},inplace=True)

In [59]:
# Modifying data & creating new columns
# create a new column
df["annual_salary"] = df["salary"] * 12

In [60]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0

In [61]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0

In [62]:
# modifying columns
df["salary"] =df["salary"]*12  # here our monthly salary is now our annual salary

In [63]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0

In [64]:
# apply() function
def categories(num):
  if num > 5:
    return "Experienced candidate"
  else:++++
    return "Learner"

In [65]:
df['experience_status'] = df['experience'].apply(categories)

In [66]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate

In [67]:
  # for performance score
def performance_category(score):
    if score >= 8:
      return "excellent"
    elif score >= 6:
      return "good"
    else:
      return "need improvement"

In [68]:
df['performance_category'] = df['performance_score'].apply(performance_category)

In [69]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,need improvement
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,excellent
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,good
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,excellent
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent

In [70]:
# map_function
department_codes = {"Engineering":"ENG", "Marketing":"MKT" , "Finance":"FIN"}
df["department_code"] = df["department"].map(department_codes)

In [71]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,need improvement,NaN
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,excellent,NaN
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,good,NaN
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,excellent,ENG
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent,NaN

In [72]:
df.sort_values(by="employee_id")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code
9,101,Ananya Malhotra,engineering,Hyderabad,24.000000,823092.0,2,8,0,2023-10-21,823092.0,Learner,excellent,NaN
84,102,Rahul Menon,Engineering,Hyderabad,38.000000,1018440.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,good,ENG
87,103,Ananya Nayak,Sales,Delhi,38.000000,821880.0,9,6,6,2021-11-19,821880.0,Experienced candidate,good,NaN
51,104,Ritu Iyer,Marketing,Bangalore,34.000000,762888.0,8,7,20,2021-05-10,762888.0,Experienced candidate,good,MKT
15,105,Vivek Pillai,Engineering,Pune,39.000000,755634.0,9,4,5,2024-06-05,755634.0,Experienced candidate,need improvement,ENG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,192,Divya Verma,HR,Delhi,40.000000,796356.0,12,7,13,2022-09-10,796356.0,Experienced candidate,good,NaN
98,193,Priya Nayak,HR,Hyderabad,23.000000,681852.0,3,9,16,2019-08-07,681852.0,Learner,excellent,NaN
34,194,Pooja Menon,Engineering,Chennai,30.861702,915372.0,7,4,9,2022-07-28,915372.0,Experienced candidate,need improvement,ENG
78,195,Pooja Nair,Finance,Hyderabad,33.000000,832752.0,6,6,4,2023-01-13,832752.0,Experienced candidate,good,FIN
43,196,Sanjay Pillai,Marketing,Bangalore,30.861702,726036.0,0,8,15,2022-11-08,726036.0,Learner,excellent,MKT

In [73]:
# descending order
df.sort_values(by="salary",ascending=False)  # if you dont write ascending =false/true it will be sort in ascending order

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code
74,158,Tanvi Malhotra,HR,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,need improvement,NaN
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent,NaN
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,good,NaN
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,good,ENG
39,117,Pooja Malhotra,engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,excellent,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,608796.0,1,6,6,2020-04-05,608796.0,Learner,good,MKT
67,169,Swati Chatterjee,HR,Pune,33.0,597612.0,3,6,11,2021-08-20,597612.0,Learner,good,NaN
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,596316.0,0,4,7,2018-08-27,596316.0,Learner,need improvement,MKT
36,167,Meera Malhotra,HR,Hyderabad,31.0,585864.0,4,5,4,2022-06-24,585864.0,Learner,need improvement,NaN
26,141,Manish Kulkarni,HR,Chennai,27.0,550020.0,3,8,13,2022-07-21,550020.0,Learner,excellent,NaN

In [74]:
# you can get list of department/any column diffent values list
df["department"].unique()

array(['Data Science', 'engineering', 'Engineering', 'Sales', 'HR',
       'Marketing', ' Marketing ', 'Finance', ' Finance ', ' HR ',
       'FINANCE', 'SALES', 'MARKETING'], dtype=object)

In [75]:
# To remove extra values like same but diffent because of space and etc
df["department"] = df["department"].str.strip().str.title()

In [76]:
df["department"].unique()   # now can only get diffent values

array(['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing',
       'Finance'], dtype=object)

In [77]:
# if you want sort this with some string
# first make a list of all diffent value
result = df.sort_values(by = ["department","salary"],ascending=[True,False])
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent,NaN
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,good,NaN
59,190,Swati Bose,Data Science,Mumbai,22.0,941580.0,0,8,18,2022-11-22,941580.0,Learner,excellent,NaN
24,170,Rahul Nair,Data Science,Kolkata,30.0,917100.0,5,2,4,2021-06-25,917100.0,Learner,need improvement,NaN
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,915204.0,5,6,3,2023-01-24,915204.0,Learner,good,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,163,Rahul Chatterjee,Sales,Kolkata,25.0,720180.0,0,8,9,2023-05-10,720180.0,Learner,excellent,NaN
17,178,Vikram Kapoor,Sales,Chennai,29.0,694296.0,3,7,1,2020-06-26,694296.0,Learner,good,NaN
44,128,Rohan Chatterjee,Sales,Mumbai,26.0,634344.0,1,3,7,2022-08-04,634344.0,Learner,need improvement,NaN
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,630876.0,5,7,8,2021-02-12,630876.0,Learner,good,NaN
5,140,Rahul Gupta,Sales,Hyderabad,23.0,628848.0,0,9,13,2018-12-27,628848.0,Learner,excellent,NaN

In [78]:
# ranking

df["salary_rank"] = df["salary"].rank(ascending=False)
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,need improvement,NaN,26.0
1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,excellent,NaN,13.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,good,NaN,28.0
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,excellent,ENG,27.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,Marketing,Chennai,22.000000,668880.0,0,5,22,2020-04-22,668880.0,Learner,need improvement,NaN,82.0
96,172,Neha Desai,Hr,Chennai,22.000000,627000.0,0,5,7,2020-11-14,627000.0,Learner,need improvement,NaN,90.0
97,115,Neha Reddy,Marketing,Chennai,43.000000,755634.0,12,4,10,2019-06-06,755634.0,Experienced candidate,need improvement,MKT,48.5
98,193,Priya Nayak,Hr,Hyderabad,23.000000,681852.0,3,9,16,2019-08-07,681852.0,Learner,excellent,NaN,76.0
99,152,Kavya Joshi,Marketing,Delhi,44.000000,833988.0,10,7,4,2022-03-25,833988.0,Experienced candidate,good,MKT,30.0

In [79]:
df.sort_values(by="salary_rank")

# NOTES :- tied values share a rank by default -two employee tied for 2nd both get rank 2.5,splitting 2 and 3
#          netween them.method ="min" gives both rank 2 instead; method="dense" avoids gaps in the rank
#          sequence entirely.Default is fine for most cases.

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code,salary_rank
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,need improvement,NaN,1.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent,NaN,2.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,good,NaN,3.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,good,ENG,4.0
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,excellent,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,608796.0,1,6,6,2020-04-05,608796.0,Learner,good,MKT,92.0
67,169,Swati Chatterjee,Hr,Pune,33.0,597612.0,3,6,11,2021-08-20,597612.0,Learner,good,NaN,93.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,596316.0,0,4,7,2018-08-27,596316.0,Learner,need improvement,MKT,94.0
36,167,Meera Malhotra,Hr,Hyderabad,31.0,585864.0,4,5,4,2022-06-24,585864.0,Learner,need improvement,NaN,95.0
26,141,Manish Kulkarni,Hr,Chennai,27.0,550020.0,3,8,13,2022-07-21,550020.0,Learner,excellent,NaN,96.0

In [80]:
# top 5 ,no full sort needed
df.nlargest(5,"salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code,salary_rank
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,need improvement,NaN,1.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,excellent,NaN,2.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,good,NaN,3.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,good,ENG,4.0
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,excellent,NaN,5.0

In [81]:
# bottom 5
df.nsmallest(5,"performance_score")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,performance_category,department_code,salary_rank
20,156,Aditya Kapoor,Data Science,Kolkata,26.0,837180.0,0,2,4,2020-04-12,837180.0,Learner,need improvement,NaN,29.0
24,170,Rahul Nair,Data Science,Kolkata,30.0,917100.0,5,2,4,2021-06-25,917100.0,Learner,need improvement,NaN,14.0
50,125,Sneha Bose,Marketing,Mumbai,32.0,679524.0,7,2,9,2023-07-12,679524.0,Experienced candidate,need improvement,MKT,77.0
76,176,Shreya Menon,Finance,Hyderabad,41.0,967164.0,9,2,18,2024-11-09,967164.0,Experienced candidate,need improvement,FIN,7.0
12,174,Divya Chatterjee,Finance,Kolkata,24.0,700488.0,1,3,12,2018-09-21,700488.0,Learner,need improvement,FIN,71.0

In [82]:
# number of unique value
df["salary"].nunique()

89

In [83]:
# if you want see what unique values are
df["city"].unique()

array(['Kolkata', 'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Bangalore',
       'Chennai'], dtype=object)

In [84]:
# to change some column data type
df['age']= df['age'].astype(int)

In [85]:
# Grouping and Aggregation
# for this u can use groupby()
# it works in three stages:split the data into group,apply a calculation to each group separatly,then cambine the results back into one table
df.groupby("city")   # now city is one kind of separete object

In [86]:
df.groupby("city")["age"].mean()  # you can get mean of age in separate city

city
Bangalore    33.500000
Chennai      29.400000
Delhi        33.000000
Hyderabad    30.892857
Kolkata      28.000000
Mumbai       27.666667
Pune         31.642857
Name: age, dtype: float64

In [87]:
# to see max salary in some city
df.groupby("city")['salary'].sum()

city
Bangalore     8226726.0
Chennai       7668690.0
Delhi        10063374.0
Hyderabad    21638088.0
Kolkata       9398976.0
Mumbai        7300476.0
Pune         10569330.0
Name: salary, dtype: float64

In [88]:
# there are other aggreations
# 1. sum() -total sum of all elements
# 2. mean() - average of elelment
# 3. median() - middle value
# 4. min() - miniumum value
# 5. max() - maximum value
# 6. count() - total lenght/size of axis// only count the non-null ones
# 7. std() - simple standard deviation
# 8. size() - count every row in the group

In [89]:
# grouping muliple columns & aggregating multiple columns
df.groupby(["city","department"])["salary"].mean().round()

city       department
Bangalore  Data Science     874344.0
           Engineering      949974.0
           Finance          804189.0
           Hr               804576.0
           Marketing        744968.0
Chennai    Engineering      877548.0
           Finance          862668.0
           Hr               588510.0
           Marketing        712257.0
           Sales            694296.0
Delhi      Data Science     915204.0
           Engineering      859965.0
           Finance          797064.0
           Hr               707011.0
           Marketing        754920.0
           Sales            793140.0
Hyderabad  Data Science     978028.0
           Engineering      920766.0
           Finance          839365.0
           Hr               696999.0
           Marketing        667961.0
           Sales            692030.0
Kolkata    Data Science     867636.0
           Engineering      956886.0
           Finance          706292.0
           Hr               666504.0
           Marketing        710232.0
           Sales            720180.0
Mumbai     Data Science     941580.0
           Engineering      840165.0
           Finance          769344.0
           Hr              1060392.0
           Marketing        738162.0
           Sales            634344.0
Pune       Data Science     905976.0
           Engineering      846030.0
           Finance          735204.0
           Hr               709908.0
           Marketing        701772.0
Name: salary, dtype: float64

In [90]:
# now lets make department as a main source
df.groupby(['department','city'])['salary'].mean().round()

department    city
Data Science  Bangalore     874344.0
              Delhi         915204.0
              Hyderabad     978028.0
              Kolkata       867636.0
              Mumbai        941580.0
              Pune          905976.0
Engineering   Bangalore     949974.0
              Chennai       877548.0
              Delhi         859965.0
              Hyderabad     920766.0
              Kolkata       956886.0
              Mumbai        840165.0
              Pune          846030.0
Finance       Bangalore     804189.0
              Chennai       862668.0
              Delhi         797064.0
              Hyderabad     839365.0
              Kolkata       706292.0
              Mumbai        769344.0
              Pune          735204.0
Hr            Bangalore     804576.0
              Chennai       588510.0
              Delhi         707011.0
              Hyderabad     696999.0
              Kolkata       666504.0
              Mumbai       1060392.0
              Pune          709908.0
Marketing     Bangalore     744968.0
              Chennai       712257.0
              Delhi         754920.0
              Hyderabad     667961.0
              Kolkata       710232.0
              Mumbai        738162.0
              Pune          701772.0
Sales         Chennai       694296.0
              Delhi         793140.0
              Hyderabad     692030.0
              Kolkata       720180.0
              Mumbai        634344.0
Name: salary, dtype: float64

In [91]:
df.groupby("department")[["salary","performance_score"]].mean()  # multiple columns at once

                     salary  performance_score
department
Data Science  917409.600000           5.700000
Engineering   888458.470588           5.705882
Finance       794252.470588           5.294118
Hr            714298.500000           5.708333
Marketing     712584.000000           5.894737
Sales         711468.666667           6.555556

In [92]:
# multiple function at a time on multiple columns
df.groupby("department").agg({
    "salary":["mean","max"],
    "performance_score":"mean",
    "employee_id":"count"
}
)

                     salary            performance_score employee_id
                       mean        max              mean       count
department
Data Science  917409.600000  1058592.0          5.700000          10
Engineering   888458.470588  1018440.0          5.705882          17
Finance       794252.470588   967164.0          5.294118          17
Hr            714298.500000  1060392.0          5.708333          24
Marketing     712584.000000   833988.0          5.894737          19
Sales         711468.666667   821880.0          6.555556           9

In [93]:
department_summary = df.groupby("department").agg(
    average_salary = ("salary","mean"),
    hightest_salary= ("salary","max"),
    employee_count =("employee_id","count")
)

In [94]:
department_summary

              average_salary  hightest_salary  employee_count
department
Data Science   917409.600000        1058592.0              10
Engineering    888458.470588        1018440.0              17
Finance        794252.470588         967164.0              17
Hr             714298.500000        1060392.0              24
Marketing      712584.000000         833988.0              19
Sales          711468.666667         821880.0               9